In [1]:
# Import Libraries
import nltk
import string
import numpy as np

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.cluster import KMeans

In [2]:
# Download required NLTK data
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [3]:
text = """
Artificial Intelligence (AI) is transforming the world! It is used in healthcare, finance, education, and transportation.
Machines can learn from data, analyze patterns, and make decisions. However, AI also raises questions: Will machines replace humans?

Natural Language Processing (NLP) is a branch of AI. It helps computers understand human language; for example, chatbots, translation systems, and voice assistants.
NLP techniques include tokenization, stemming, lemmatization, and stop-word removal. These techniques improve text analysis!
"""

In [ ]:
print("\nOriginal Text:\n")
print(text)


Original Text:


Artificial Intelligence (AI) is transforming the world! It is used in healthcare, finance, education, and transportation.
Machines can learn from data, analyze patterns, and make decisions. However, AI also raises questions: Will machines replace humans?

Natural Language Processing (NLP) is a branch of AI. It helps computers understand human language; for example, chatbots, translation systems, and voice assistants.
NLP techniques include tokenization, stemming, lemmatization, and stop-word removal. These techniques improve text analysis!



In [ ]:
# Remove Punctuation

text_no_punct = text.translate(str.maketrans('', '', string.punctuation))

print("\nText After Removing Punctuation:\n")
print(text_no_punct)



Text After Removing Punctuation:


Artificial Intelligence AI is transforming the world It is used in healthcare finance education and transportation
Machines can learn from data analyze patterns and make decisions However AI also raises questions Will machines replace humans

Natural Language Processing NLP is a branch of AI It helps computers understand human language for example chatbots translation systems and voice assistants
NLP techniques include tokenization stemming lemmatization and stopword removal These techniques improve text analysis



In [ ]:
# Tokenization

tokens = word_tokenize(text_no_punct)

print("\nTokens:\n")
print(tokens)



Tokens:

['Artificial', 'Intelligence', 'AI', 'is', 'transforming', 'the', 'world', 'It', 'is', 'used', 'in', 'healthcare', 'finance', 'education', 'and', 'transportation', 'Machines', 'can', 'learn', 'from', 'data', 'analyze', 'patterns', 'and', 'make', 'decisions', 'However', 'AI', 'also', 'raises', 'questions', 'Will', 'machines', 'replace', 'humans', 'Natural', 'Language', 'Processing', 'NLP', 'is', 'a', 'branch', 'of', 'AI', 'It', 'helps', 'computers', 'understand', 'human', 'language', 'for', 'example', 'chatbots', 'translation', 'systems', 'and', 'voice', 'assistants', 'NLP', 'techniques', 'include', 'tokenization', 'stemming', 'lemmatization', 'and', 'stopword', 'removal', 'These', 'techniques', 'improve', 'text', 'analysis']


In [ ]:
#Stop Word Removal

stop_words = set(stopwords.words('english'))

filtered_words = [word for word in tokens if word.lower() not in stop_words]

print("\nAfter Stop Word Removal:\n")
print(filtered_words)



After Stop Word Removal:

['Artificial', 'Intelligence', 'AI', 'transforming', 'world', 'used', 'healthcare', 'finance', 'education', 'transportation', 'Machines', 'learn', 'data', 'analyze', 'patterns', 'make', 'decisions', 'However', 'AI', 'also', 'raises', 'questions', 'machines', 'replace', 'humans', 'Natural', 'Language', 'Processing', 'NLP', 'branch', 'AI', 'helps', 'computers', 'understand', 'human', 'language', 'example', 'chatbots', 'translation', 'systems', 'voice', 'assistants', 'NLP', 'techniques', 'include', 'tokenization', 'stemming', 'lemmatization', 'stopword', 'removal', 'techniques', 'improve', 'text', 'analysis']


In [ ]:
#Stemming

stemmer = PorterStemmer()

stemmed_words = [stemmer.stem(word) for word in filtered_words]

print("\nAfter Stemming:\n")
print(stemmed_words)



After Stemming:

['artifici', 'intellig', 'ai', 'transform', 'world', 'use', 'healthcar', 'financ', 'educ', 'transport', 'machin', 'learn', 'data', 'analyz', 'pattern', 'make', 'decis', 'howev', 'ai', 'also', 'rais', 'question', 'machin', 'replac', 'human', 'natur', 'languag', 'process', 'nlp', 'branch', 'ai', 'help', 'comput', 'understand', 'human', 'languag', 'exampl', 'chatbot', 'translat', 'system', 'voic', 'assist', 'nlp', 'techniqu', 'includ', 'token', 'stem', 'lemmat', 'stopword', 'remov', 'techniqu', 'improv', 'text', 'analysi']


In [ ]:
# Lemmatization

lemmatizer = WordNetLemmatizer()

lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]

print("\nAfter Lemmatization:\n")
print(lemmatized_words)


After Lemmatization:

['Artificial', 'Intelligence', 'AI', 'transforming', 'world', 'used', 'healthcare', 'finance', 'education', 'transportation', 'Machines', 'learn', 'data', 'analyze', 'pattern', 'make', 'decision', 'However', 'AI', 'also', 'raise', 'question', 'machine', 'replace', 'human', 'Natural', 'Language', 'Processing', 'NLP', 'branch', 'AI', 'help', 'computer', 'understand', 'human', 'language', 'example', 'chatbots', 'translation', 'system', 'voice', 'assistant', 'NLP', 'technique', 'include', 'tokenization', 'stemming', 'lemmatization', 'stopword', 'removal', 'technique', 'improve', 'text', 'analysis']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [ ]:
#Bag of Words

cv = CountVectorizer()
bow = cv.fit_transform([text])

print("Feature Names:\n", cv.get_feature_names_out())
print("\nBoW Matrix:\n", bow.toarray())

Feature Names:
 ['ai' 'also' 'analysis' 'analyze' 'and' 'artificial' 'assistants' 'branch'
 'can' 'chatbots' 'computers' 'data' 'decisions' 'education' 'example'
 'finance' 'for' 'from' 'healthcare' 'helps' 'however' 'human' 'humans'
 'improve' 'in' 'include' 'intelligence' 'is' 'it' 'language' 'learn'
 'lemmatization' 'machines' 'make' 'natural' 'nlp' 'of' 'patterns'
 'processing' 'questions' 'raises' 'removal' 'replace' 'stemming' 'stop'
 'systems' 'techniques' 'text' 'the' 'these' 'tokenization' 'transforming'
 'translation' 'transportation' 'understand' 'used' 'voice' 'will' 'word'
 'world']

BoW Matrix:
 [[3 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 1 1 2 1 1 2
  1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#TF-IDF

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform([text])

print("Feature Names:\n", tfidf.get_feature_names_out())
print("\nTF-IDF Matrix:\n", tfidf_matrix.toarray())

Feature Names:
 ['ai' 'also' 'analysis' 'analyze' 'and' 'artificial' 'assistants' 'branch'
 'can' 'chatbots' 'computers' 'data' 'decisions' 'education' 'example'
 'finance' 'for' 'from' 'healthcare' 'helps' 'however' 'human' 'humans'
 'improve' 'in' 'include' 'intelligence' 'is' 'it' 'language' 'learn'
 'lemmatization' 'machines' 'make' 'natural' 'nlp' 'of' 'patterns'
 'processing' 'questions' 'raises' 'removal' 'replace' 'stemming' 'stop'
 'systems' 'techniques' 'text' 'the' 'these' 'tokenization' 'transforming'
 'translation' 'transportation' 'understand' 'used' 'voice' 'will' 'word'
 'world']

TF-IDF Matrix:
 [[0.29138576 0.09712859 0.09712859 0.09712859 0.38851434 0.09712859
  0.09712859 0.09712859 0.09712859 0.09712859 0.09712859 0.09712859
  0.09712859 0.09712859 0.09712859 0.09712859 0.09712859 0.09712859
  0.09712859 0.09712859 0.09712859 0.09712859 0.09712859 0.09712859
  0.09712859 0.09712859 0.09712859 0.29138576 0.19425717 0.19425717
  0.09712859 0.09712859 0.19425717 0.097

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 48.9 MB/s eta 0:00:00


In [ ]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk


In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
# Preprocessing

tokens = word_tokenize(text.lower())

In [ ]:
# Convert into sentences (Word2Vec expects list of lists)
sentences = [tokens]

In [ ]:
# Check Vocabulary (IMPORTANT DEBUG)

print("Vocabulary:\n", list(model.wv.index_to_key))


Vocabulary:
 [',', '.', 'and', 'is', 'ai', 'techniques', 'nlp', 'language', 'machines', 'it', '!', ')', '(', 'analysis', 'text', 'improve', 'these', 'removal', 'stop-word', 'lemmatization', 'stemming', 'tokenization', 'include', 'assistants', 'voice', 'systems', 'translation', 'chatbots', 'example', 'for', ';', 'human', 'understand', 'computers', 'helps', 'of', 'branch', 'a', 'processing', 'natural', '?', 'humans', 'replace', 'will', ':', 'questions', 'raises', 'also', 'however', 'decisions', 'make', 'patterns', 'analyze', 'data', 'from', 'learn', 'can', 'transportation', 'education', 'finance', 'healthcare', 'in', 'used', 'world', 'the', 'transforming', 'intelligence', 'artificial']


In [ ]:
# Train Word2Vec Model

model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4)


In [ ]:
print("\nSimilarity between ai and intelligence:",
      model.wv.similarity('ai', 'intelligence'))

print("Similarity between data and patterns:",
      model.wv.similarity('data', 'patterns'))

print("Similarity between language and processing:",
      model.wv.similarity('language', 'processing'))

print("Similarity between machines and humans:",
      model.wv.similarity('machines', 'humans'))


Similarity between ai and intelligence: 0.14396355
Similarity between data and patterns: -0.12598605
Similarity between language and processing: -0.1123665
Similarity between machines and humans: -0.023434624


In [4]:
#COSINE SIMILARITY

sentences = [
    "AI is transforming the world",
    "Machines learn from data",
    "NLP helps computers understand language"
]

In [5]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(sentences)

In [6]:
similarity_matrix = cosine_similarity(vectors)

In [8]:
print("\n COSINE SIMILARITY MATRIX \n")
print(similarity_matrix)


 COSINE SIMILARITY MATRIX 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# TEXT CLASSIFICATION (SUPERVISED)

docs = [
    "AI is powerful",
    "Machine learning is useful",
    "I love programming",
    "Python is great",
    "I hate bugs",
    "Errors are frustrating"
]

In [11]:
 # 1=Positive
 # 0=Negative
labels = [1, 1, 1, 1, 0, 0]

In [12]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

In [14]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [15]:
print("\n CLASSIFICATION PREDICTION ")
print(model.predict(X_test))


 CLASSIFICATION PREDICTION 
[1 1]


In [20]:
#CLUSTERING (UNSUPERVISED)

texts_un = [
    "AI and machine learning",
    "Deep learning models",
    "Natural language processing",
    "Football match",
    "Cricket game",
    "Sports tournament"
]

In [21]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts_un)

In [23]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X)

KMeans(n_clusters=2, random_state=42)

In [24]:
print("\nCLUSTERING RESULT")
for i, text in enumerate(texts):
    print(f"{text} -> Cluster {kmeans.labels_[i]}")


CLUSTERING RESULT
AI and machine learning -> Cluster 0
Deep learning models -> Cluster 0
Natural language processing -> Cluster 0
Football match -> Cluster 0
Cricket game -> Cluster 0
Sports tournament -> Cluster 1
